name: Deploy as UPM
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: upm
        FOLDER: src/Assets/Console
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
